version: '3.8'

volumes:
  rm_memories_mngmt_mongodb_data: {}

services:

  rm-memories-mngmt-mongodb:
    image: mongo:4.4.0
    container_name: rm-memories-mngmt-mongodb
    restart: always
    volumes:
      - rm_memories_mngmt_mongodb_data:/data/db
    env_file:
      - ./mongodb.base.env
    healthcheck:
      test: bash -c "</dev/tcp/rm-memories-mngmt-mongodb/27017 && exit 0 || exit 1"
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
